test-ubuntu:
  image: ubuntu:latest
  script:
    - dash -c ". $PWD/.config/sh/init.sh"
    - dash -c ". $PWD/.profile"
    - bash -c ". $PWD/.config/sh/init.sh"
    - bash -c ". $PWD/.bashrc"
    - bash -c ". $PWD/.profile"

test-zsh:
  image: zshusers/zsh
  script:
    - zsh -c ". $PWD/.config/sh/init.sh"
    - zsh -c ". $PWD/.profile"
