test-dash:
  image: ubuntu:latest
  script:
    - dash -c "env"
    - dash -c "pwd"
    - dash -c "ls -a"
    - dash -c ". .profile"

test-bash:
  image: ubuntu:latest
  script:
    - bash -c "env"
    - bash -c "pwd"
    - bash -c "ls -a"
    - bash -c ". $PWD/.profile"
    - bash -c ". $PWD/.bashrc"

test-zsh:
  image: zshusers/zsh
  script:
    - zsh -c "env"
    - zsh -c "pwd"
    - zsh -c "ls -a"
    - zsh -c ". $PWD/.profile"
    - zsh -c ". $PWD/.bashrc"
