categories = ["Add", "Tweak", "Deprecate", "Change", "Move", "Fix", "Modify", "Improve", "Remove", "Simplify", "Update", "Refactor", "Implement", "Expand", "Extend"]
category_delimiters = ["[", "]"]
colored_output = false
enable_debug = true
excluded_commit_tags = []
enable_footers = false
show_commit_hash = false
show_prefix = false
sort_by = "date"
template_prefix = "JIRA-1234"
