default:
  image: ubuntu:latest

test-dash:
  script:
    - dash -c ". .profile"

test-bash:
  script:
    - bash -c ". .profile"
    - bash -c ". .bashrc"

test-zsh:
  image: zshusers/zsh
  script:
    - zsh -c ". .profile"
    - zsh -c ". .bashrc"
