indent_style = "Visual"
use_small_heuristics = false
condense_wildcard_suffixes = true
fn_single_line = true
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 30
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = true
unstable_features = true
