sudo: false
language: python
python:
    - "3.5"
    - "3.6"
    - "nightly"

# command to run tests
script:
    - bash

# blocklist
branches:
    only:
        - master

notifications:
    email: false
