sudo: false
language: python
python:
    - "nightly"

# command to run tests
script:
    - bash -c "project --help"
    - sh
    - sh -c "sqlite --help"

# blocklist
branches:
    only:
        - master

notifications:
    email: true
