# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/norbert/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-12.4
# extra-deps:
# - base-4.11.1.0
# - attoparsec-0.13.2.2
# - filepath-1.4.2
# - bytestring-0.10.8.2
# - directory-1.3.1.5
# - foundation-0.0.21
#
