[v1]
"bat 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-count 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-count"]
"cargo-edit 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-fix 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fix"]
"cargo-graph 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-graph"]
"cargo-script 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-script", "run-cargo-script"]
"cargo-tree 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 1.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-watch 7.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"clippy 0.0.209 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clippy", "clippy-driver"]
"exa 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 7.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fselect 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fselect"]
"git-journal 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-journal"]
"gluon_repl 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gluon"]
"hashdir 0.1.0 (git+https://github.com/Wilfred/remacs#328b3a5e018466c66eeceba26e3e73e23b935ee9)" = ["hashdir"]
"hyperfine 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"ion-shell 1.0.0-alpha (git+https://gitlab.redox-os.org/redox-os/ion/#bf51b42128df399a5ff6dbd9057a12d39537040f)" = ["ion"]
"mdbook 0.1.9-alpha.0 (git+https://github.com/rust-lang-nursery/mdBook.git#0ac36f2183ca869ec670478355a099ea1fe8cd3e)" = ["mdbook"]
"parallel 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["parallel"]
"pulldown-cmark 0.1.2 (git+https://github.com/google/pulldown-cmark#dad39d1be53015eb940c2672facba97cd98fbff6)" = ["pulldown-cmark"]
"racer 2.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rls 0.122.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rls"]
"rustfmt-nightly 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "git-rustfmt", "rustfmt", "rustfmt-format-diff"]
"rusti 0.0.1 (git+https://github.com/murarth/rusti#2dddea34eb70044eb24cf8c54bb3cb8fccfafbb6)" = ["rusti"]
"rusty-tags 2.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-tags"]
"shellharden 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["shellharden"]
"skim 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"tokei 7.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"watchexec 1.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"wtftw 0.4.4 (git+https://github.com/Kintaro/wtftw#ebf5f9f1c08cfc5f3084c3eadcb16da029370b61)" = ["wtftw"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
