[v1]
"bat 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo 0.30.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo"]
"cargo-add 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add"]
"cargo-count 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-count"]
"cargo-edit 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-rm", "cargo-upgrade"]
"cargo-fix 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fix"]
"cargo-graph 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-graph"]
"cargo-script 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-script", "run-cargo-script"]
"cargo-tree 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tree"]
"cargo-update 1.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-watch 7.0.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"clippy 0.0.209 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clippy", "clippy-driver"]
"exa 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fcat 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fcat"]
"fd-find 7.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fselect 0.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["fselect"]
"git-journal 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-journal"]
"gluon_repl 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gluon"]
"hashdir 0.1.0 (git+https://github.com/Wilfred/remacs#328b3a5e018466c66eeceba26e3e73e23b935ee9)" = ["hashdir"]
"hyperfine 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"ion-shell 1.0.0-alpha (git+https://gitlab.redox-os.org/redox-os/ion/#bf51b42128df399a5ff6dbd9057a12d39537040f)" = ["ion"]
"mdbook 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"parallel 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["parallel"]
"pulldown-cmark 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["pulldown-cmark"]
"racer 2.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"ripgrep 0.10.0 (git+https://github.com/BurntSushi/ripgrep#7ebed3ace695aa89ae2bfed2c02d5ab005da1dce)" = ["rg"]
"rls 0.122.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rls"]
"rustfmt 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "rustfmt"]
"rustfmt-nightly 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-rustfmt", "rustfmt-format-diff"]
"rusti 0.0.1 (git+https://github.com/murarth/rusti#2dddea34eb70044eb24cf8c54bb3cb8fccfafbb6)" = ["rusti"]
"rusty-tags 3.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-tags"]
"shellharden 4.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["shellharden"]
"skim 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"tokei 8.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"watchexec 1.9.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"wtftw 0.4.4 (git+https://github.com/Kintaro/wtftw#ebf5f9f1c08cfc5f3084c3eadcb16da029370b61)" = ["wtftw"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
