[v1]
"bat 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-edit 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
"cargo-fix 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fix"]
"clippy 0.0.209 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-clippy", "clippy-driver"]
"exa 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 7.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"parallel 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["parallel"]
"racer 2.0.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rustfmt-nightly 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-fmt", "git-rustfmt", "rustfmt", "rustfmt-format-diff"]
"skim 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"tokei 7.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"watchexec 1.8.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"xsv 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xsv"]
