# vim:ft=yaml:
jobs: 4
templates:
  params:
    author-email: norbertlogiewa96@gmail.com
    copyright: MIT
    github-username: nl253
    author-name: Norbert Logiewa
system-ghc: false
install-ghc: true
ghc-options:
  "$everything": -O2 -XDeriveFunctor -XDeriveFoldable -XDeriveTraversable -XPartialTypeSignatures -XTupleSections -XDeriveAnyClass -XEmptyDataDecls -XPostfixOperators
  # "$everything": -O2 -XFlexibleContexts -XTupleSections -XDeriveAnyClass -XEmptyDataDecls -XPostfixOperators -XGADTs
  # "$everything": -O2 -XFlexibleContexts -XOverloadedStrings -XTupleSections -XDeriveAnyClass -XEmptyDataDecls -XPostfixOperators -XGADTs -XOverloadedLists
