# vim:ft=yaml:
jobs: 4
templates:
  params:
    author-email: norbertlogiewa96@gmail.com
    copyright: MIT
    github-username: nl253
    author-name: Norbert Logiewa
system-ghc: false
install-ghc: true
ghc-options:
  "$everything": -XBangPatterns -XPatternGuards -XApplicativeDo -XBinaryLiterals -XDeriveAnyClass -XScopedTypeVariables -XDeriveGeneric -XDeriveFoldable -XDeriveFunctor -XDeriveTraversable -XEmptyDataDecls -XFunctionalDependencies -XGADTs -XKindSignatures -XLambdaCase -XMonadComprehensions -XMultiParamTypeClasses -XMultiWayIf -XNamedWildCards -XNumDecimals -XParallelListComp -XPartialTypeSignatures -XPostfixOperators -XTupleSections -XTypeOperators -XViewPatterns -XFlexibleContexts  -XFlexibleInstances -XOverloadedStrings -XOverloadedLists
